version: '3'

services:

  dspot-db:
    image: bitnami/mariadb:10.5.8
    container_name: dspot-db
    ports:
      - 33062:3306
    env_file:
      - .env
    environment:
      TZ: "Europe/Warsaw"
      ALLOW_EMPTY_PASSWORD: "yes"
      MARIADB_SKIP_TEST_DB: "yes"
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}

  dspot-api:
    container_name: dspot-api
    restart: on-failure
    tty: true
    image: bitnami/laravel:9.1.8
    ports:
      - 8085:8000
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - dspot-db
